pom.xml
src/main/java/be/xplore/pricescraper/PriceScraperApplication.java
src/main/java/be/xplore/pricescraper/domain/shopping/Item.java
src/main/java/be/xplore/pricescraper/domain/shopping/ItemPrice.java
src/main/java/be/xplore/pricescraper/domain/shopping/Shop.java
src/main/java/be/xplore/pricescraper/strategies/ColruytScraper.java
src/main/java/be/xplore/pricescraper/strategies/Scraper.java
src/test/java/be/xplore/pricescraper/PriceScraperApplicationTests.java
src/test/java/be/xplore/pricescraper/strategies/ScraperTests.java

feat: architecture setup

---

pom.xml
src/main/resources/application.properties

feat: added h2 in-memory db

---

.github/workflows/build.yml
pom.xml

Resolves #2 
- Added configuration for sonarcloud code analysis

Sonarcloud configuration

---

.github/workflows/build.yml
pom.xml

Resolves #16 
Enabled code coverage on sonarcloud

feat: add code coverage on sonarcloud

---

pom.xml
src/main/java/be/xplore/pricescraper/PriceScraperApplication.java
src/main/java/be/xplore/pricescraper/domain/shopping/Item.java
src/main/java/be/xplore/pricescraper/domain/shopping/ItemPrice.java
src/main/java/be/xplore/pricescraper/domain/shopping/Shop.java
src/main/java/be/xplore/pricescraper/strategies/ColruytScraper.java
src/main/java/be/xplore/pricescraper/strategies/Scraper.java
src/main/resources/checkstyle.xml

Resolves #12 
- Added checkstyle configuration
- Added checkstyle to mvn verify

feat: added checkstyle configuration

---

pom.xml
src/main/java/be/xplore/pricescraper/PriceScraperApplication.java
src/main/java/be/xplore/pricescraper/utils/ProductMatcher.java
src/main/resources/application.properties
src/test/java/be/xplore/pricescraper/utils/ProductMatcherTests.java

Resolves #14 
feat: adding product matching logic

feat: product matching logic based on ingredients

---

.github/workflows/build.yml
pom.xml

Resolves #30 
- Changed configuration so checkstyle runs during verify phase

fix: checkstyle runs in verify phase

---

tests/src/test/java/ShoppingListServiceIT.java

- Fixed shopping lists integration tests (tests would sometimes give conflicts because they are run asynchronously)
- Improved performance

fix: fixed shopping lists integration tests

---

adapters/outgoing/jpa/src/main/java/be/xplore/pricescraper/repositories/implementations/ItemRepositoryImpl.java
core/src/main/java/be/xplore/pricescraper/repositories/ItemRepository.java
core/src/main/java/be/xplore/pricescraper/services/ItemServiceImpl.java

- Flushed entity before referencing

fix: track item reference of transient entity

---

adapters/incoming/rest/src/main/java/be/xplore/pricescraper/config/SecurityConfig.java
adapters/incoming/rest/src/main/java/be/xplore/pricescraper/controllers/AuthController.java
adapters/incoming/rest/src/main/java/be/xplore/pricescraper/dtos/NewTokenDto.java
adapters/incoming/rest/src/main/java/be/xplore/pricescraper/dtos/RefreshAndAccessTokenDto.java
adapters/incoming/rest/src/main/java/be/xplore/pricescraper/utils/security/JwtProvider.java
adapters/incoming/rest/src/main/java/be/xplore/pricescraper/utils/security/JwtSuccessHandler.java
adapters/incoming/rest/src/test/java/be/xplore/pricescraper/controllers/ShoppingListControllerTests.java
adapters/incoming/rest/src/test/java/be/xplore/pricescraper/jwt/JwtSuccessHandlerTests.java
adapters/incoming/rest/src/test/java/be/xplore/pricescraper/utils/UserUtilsTests.java
adapters/outgoing/jpa/src/main/java/be/xplore/pricescraper/entity/users/RefreshTokenEntity.java
adapters/outgoing/jpa/src/main/java/be/xplore/pricescraper/entity/users/UserEntity.java
adapters/outgoing/jpa/src/main/java/be/xplore/pricescraper/repositories/implementations/ItemRepositoryImpl.java
adapters/outgoing/jpa/src/main/java/be/xplore/pricescraper/repositories/implementations/RefreshTokenRepositoryImpl.java
adapters/outgoing/jpa/src/main/java/be/xplore/pricescraper/repositories/implementations/ShopRepositoryImpl.java
adapters/outgoing/jpa/src/main/java/be/xplore/pricescraper/repositories/implementations/TrackedItemRepositoryImpl.java
adapters/outgoing/jpa/src/main/java/be/xplore/pricescraper/repositories/jpa/RefreshTokenJpaRepository.java
adapters/outgoing/jpa/src/test/java/be/xplore/pricescraper/repositories/UserRepositoryTests.java
core/src/main/java/be/xplore/pricescraper/domain/users/RefreshToken.java
core/src/main/java/be/xplore/pricescraper/domain/users/User.java
core/src/main/java/be/xplore/pricescraper/repositories/ItemRepository.java
core/src/main/java/be/xplore/pricescraper/repositories/RefreshTokenRepository.java
core/src/main/java/be/xplore/pricescraper/repositories/TrackedItemRepository.java
core/src/main/java/be/xplore/pricescraper/services/ItemServiceImpl.java
core/src/main/java/be/xplore/pricescraper/services/RefreshTokenService.java
core/src/main/java/be/xplore/pricescraper/services/RefreshTokenServiceImpl.java
core/src/test/java/be/xplore/pricescraper/domain/UserTests.java
core/src/test/java/be/xplore/pricescraper/services/RefreshTokenServiceTests.java
tests/src/test/java/be/xplore/pricescraper/ItemServiceIT.java

feat: refresh token

---

adapters/outgoing/jpa/src/main/java/be/xplore/pricescraper/entity/shops/ItemEntity.java
adapters/outgoing/jpa/src/main/java/be/xplore/pricescraper/repositories/implementations/ItemRepositoryImpl.java
adapters/outgoing/scrapers/ahscraper/src/main/java/be/xplore/pricescraper/scrapers/detail/AhBeScraper.java
adapters/outgoing/scrapers/aldiscraper/src/main/java/be/xplore/pricescraper/scrapers/AldiBeScraper.java
adapters/outgoing/scrapers/carrefourscraper/src/main/java/be/xplore/pricescraper/scrapers/detail/CarrefourBeScraper.java
adapters/outgoing/scrapers/lildscraper/src/main/java/be/xplore/pricescraper/scrapers/LidlBeScraper.java
adapters/outgoing/scrapers/localdummyscraper/src/main/java/be/xplore/pricescraper/scrapers/LocalDummyScraper.java
adapters/outgoing/scrapers/scraper/src/main/java/be/xplore/pricescraper/scrapers/ItemDetailScraper.java
application/src/main/java/be/xplore/pricescraper/seed/ItemSeed.java
core/src/main/java/be/xplore/pricescraper/dtos/ShopItem.java
core/src/main/java/be/xplore/pricescraper/services/ItemServiceImpl.java

feat: Ingredients

---

adapters/factories/itemmatchercombinerfactory/src/main/java/be/xplore/pricescraper/matchers/factories/ItemMatcherCombinerFactoryImpl.java
adapters/factories/itemmatchercombinerfactory/src/test/java/be/xplore/pricescraper/matchers/ItemMatcherCombinerFactoryTests.java
adapters/incoming/rest/src/main/java/be/xplore/pricescraper/config/SecurityConfig.java
adapters/incoming/rest/src/main/java/be/xplore/pricescraper/utils/security/JwtSuccessHandler.java
adapters/matchers/combiners/src/main/java/be/xplore/pricescraper/matchers/combiners/WeightedItemMatcherCombiner.java
adapters/matchers/imagerecognitionmatcher/src/main/java/be/xplore/pricescraper/matchers/ImageRecognitionMatcher.java
adapters/matchers/ingredientmatcher/src/main/java/be/xplore/pricescraper/matchers/IngredientMatcher.java
adapters/matchers/ingredientmatcher/src/test/java/be/xplore/pricescraper/matchers/ItemIngredientMatcherTests.java
adapters/matchers/itemmatcher/src/main/java/be/xplore/pricescraper/matchers/ItemMatcher.java
adapters/matchers/matcherutils/pom.xml
adapters/matchers/matcherutils/src/main/java/be/xplore/pricescraper/matchers/utils/MatchStringUtils.java
adapters/matchers/pom.xml
adapters/matchers/titlematcher/pom.xml
adapters/matchers/titlematcher/src/main/java/be/xplore/pricescraper/matchers/TitleMatcher.java
adapters/matchers/titlematcher/src/test/java/be/xplore/pricescraper/matchers/TitleMatcherTests.java
application/pom.xml
application/src/main/java/be/xplore/pricescraper/config/SpringConfig.java
core/src/main/java/be/xplore/pricescraper/exceptions/CombinerInitializeException.java
core/src/main/java/be/xplore/pricescraper/factories/ItemMatcherCombinerFactory.java
core/src/main/java/be/xplore/pricescraper/services/ItemServiceImpl.java

Resolves #57 
- Added title matcher
- Refactored combiner factory
- Added title matcher in config to combiner
- Small fix to security config (frontend url)

feat: add title based matcher

---

adapters/outgoing/scrapers/ahscraper/src/main/java/be/xplore/pricescraper/scrapers/detail/AhBeScraper.java

fix: scraping discounts from ah

---

.github/workflows/build.yml
.github/workflows/deploy.yml

Resolves #91 
- Refactored deploy workflow to run separately

feat: refactored deploy workflow

---

adapters/matchers/combiners/src/main/java/be/xplore/pricescraper/matchers/combiners/WeightedItemMatcherCombiner.java
adapters/matchers/combiners/src/test/java/be/xplore/pricescraper/matchers/combiners/WeightedItemMatcherCombinerTests.java
adapters/matchers/ingredientmatcher/src/test/java/be/xplore/pricescraper/matchers/ItemIngredientMatcherTests.java
adapters/matchers/nutritionvaluematcher/pom.xml
adapters/matchers/nutritionvaluematcher/src/main/java/be/xplore/pricescraper/matchers/NutritionValueMatcher.java
adapters/matchers/nutritionvaluematcher/src/test/java/be/xplore/pricescraper/matchers/NutritionValueMatcherTests.java
adapters/matchers/pom.xml
adapters/matchers/titlematcher/src/test/java/be/xplore/pricescraper/matchers/TitleMatcherTests.java
adapters/matchers/unitmatcher/src/test/java/be/xplore/pricescraper/matchers/UnitMatcherTests.java
adapters/outgoing/jpa/src/main/java/be/xplore/pricescraper/entity/shops/ItemEntity.java
adapters/outgoing/jpa/src/main/java/be/xplore/pricescraper/repositories/implementations/ItemRepositoryImpl.java
adapters/outgoing/scrapers/carrefourscraper/src/main/java/be/xplore/pricescraper/scrapers/detail/CarrefourBeScraper.java
adapters/outgoing/scrapers/carrefourscraper/src/test/java/be/xplore/pricescraper/scrapers/detail/CarrefourBeScraperTests.java
application/pom.xml
application/src/main/java/be/xplore/pricescraper/config/SpringConfig.java
application/src/main/java/be/xplore/pricescraper/seed/ItemSeed.java
core/src/main/java/be/xplore/pricescraper/domain/shops/Item.java
core/src/main/java/be/xplore/pricescraper/services/ItemServiceImpl.java
core/src/test/java/be/xplore/pricescraper/services/ItemServiceTests.java
report/pom.xml

Resolves #100 
- Added nutrition value matcher
- Updated combiner weights

feat: added nutrition value matcher

---

.github/workflows/deploy.yml
adapters/incoming/rest/src/main/java/be/xplore/pricescraper/config/SecurityConfig.java

- Fix of cors for deployed version

feat: deployment cors

---

adapters/matchers/combiners/src/main/java/be/xplore/pricescraper/matchers/combiners/WeightedItemMatcherCombiner.java
adapters/matchers/ingredientmatcher/src/main/java/be/xplore/pricescraper/matchers/IngredientMatcher.java
adapters/matchers/nutritionvaluematcher/src/main/java/be/xplore/pricescraper/matchers/NutritionValueMatcher.java
adapters/matchers/nutritionvaluematcher/src/test/java/be/xplore/pricescraper/matchers/NutritionValueMatcherTests.java

- Fixed issue on matching energy value

fix: nutrition value matches correctly for energy

---

readme.md

fix: environment variables

---

adapters/outgoing/jpa/src/main/java/be/xplore/pricescraper/entity/users/ShoppingListEntity.java
adapters/outgoing/jpa/src/main/java/be/xplore/pricescraper/entity/users/UserEntity.java

Resolves #114 
- Duplicate line entities on fetch fixed

fix: shopping lis line duplicated fixed

---

Dockerfile
adapters/matchers/nutritionvaluematcher/src/main/java/be/xplore/pricescraper/matchers/NutritionValueMatcher.java
core/src/main/java/be/xplore/pricescraper/services/ItemServiceImpl.java

- Fixed scraper errors caused by nutrition value matcher
- changed frontend url

Fixed scraper errors and frontend url

---

Dockerfile

- Remove ram limit in dockerfile

fix: removed dockerfile ram limit
